services:
  nextjs:
    build:
      context: .
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/colab
    depends_on:
      - db
    develop:
      watch:
        - path: .
          target: /app
          action: sync
        - path: ./package.json
          target: /app/package.json
          action: rebuild

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=colab
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

